$(function(){
	/*第1块盒子*/
	//切换背景图
	$(".template-list img").click(function(){
		$(this).siblings("img").css("border","solid 0px red")
		$(this).css("border","solid 2px red");
		console.log($(this).attr("src"));
		$(".box-back").css("background","url("+$(this).attr("src")+") no-repeat 0px 0px/100% 100%");
	})
	//切换标题背景图
	$(".titleimg-list img").click(function(){
		$(this).siblings("img").css("border","solid 0px red")
		$(this).css("border","solid 2px red");
		if($(this).attr("class")=="nobackground"){
			$(".content-title").css("background","none");
		}else{
			$(".content-title").css("background","url("+$(this).attr("src")+") no-repeat 0px 0px/100% 100%");
		}
		
	})
	
	/*第2块盒子*/
	$(".btn2").click(function(){
		//模板宽度
		$(this).parent().siblings(".template-right").find(".box-back").css("width",$(".box2w").val()+"px");
		//大标题内容
		$(".conference").html($(".bzdh").val());
		//大标题文字大小：
		$(".conference").css("font-size",$(".bzdh-size").val()+"px");
		//英文内容：
		$(".english").html($(".yw").val());
		//英文字体大小：
		$(".english").css("font-size",$(".yw-size").val()+"px");
		//小标题内容：
		$(".conference2").html($(".xbt").val());
		//小标题字体大小：
		$(".conference2").css("font-size",$(".xbt-size").val()+"px");
		//公司名称：
		$(".companyname").html($(".gs").val());
		//公司字体大小：
		$(".companyname").css("font-size",$(".gs-size").val()+"px");
		//时间：
		$(".mytime").html($(".sj").val());
		//时间字体大小：
		$(".mytime").css("font-size",$(".sj-size").val()+"px");
	})
	//大标题文字颜色：
	$(".bzdh-color").change(function(){
		$(".conference").css("color",$(this).val());
	})
	//英文文字颜色：
	$(".yw-color").change(function(){
		$(".english").css("color",$(this).val());
	})
	//小标题文字颜色：
	$(".xbt-color").change(function(){
		$(".conference2").css("color",$(this).val());
	})
	//公司名称文字颜色：
	$(".gs-color").change(function(){
		$(".companyname").css("color",$(this).val());
	})
	//时间文字颜色：
	$(".sj-color").change(function(){
		$(".mytime").css("color",$(this).val());
	})
	
	/*第3块盒子*/
	$(".btn3").click(function(){
		//模板宽度
		$(this).parent().siblings(".template-right").find(".box-back").css("width",$(this).siblings(".set-list").find(".box2w").val());
		//大标题内容：
		$(this).parent().siblings(".template-right").find(".content-title").html($(this).siblings(".set-list").find(".dbt").val());
		//大标题字体大小：
		$(this).parent().siblings(".template-right").find(".content-title").css("font-size",$(this).siblings(".set-list").find(".dbt-size").val()+"px");
		//称呼：
		$(".name3").html($(".ch").val());
		//称呼字体大小：
		$(".name3").css("font-size",$(".ch-size").val()+"px");
		//段落1：
		$(".w3p1").html($(".d1").val());
		//段落2：
		$(".w3p2").html($(".d2").val());
		//段落3：
		$(".w3p3").html($(".d3").val());
		//段落字体大小：
		$(".w3p1,.w3p2,.w3p3").css("font-size",$(".d-size").val()+"px");
		//公司名称：
		$(".companyname3").html($(".gs3").val());
		//公司字体大小：
		$(".companyname3").css("font-size",$(".gs3-size").val()+"px");
		//时间：
		$(".mytime3").html($(".sj3").val());
		//时间字体大小：
		$(".mytime3").css("font-size",$(".sj3-size").val()+"px");
	})
	//大标题颜色（公用）
	$(".dbt-color").change(function(){
		$(this).parents(".template").find(".content-title").css("color",$(this).val());
	})
	//称呼文字颜色：
	$(".ch-color").change(function(){
		$(".name3").css("color",$(this).val());
	})
	//段落文字颜色：
	$(".d-color").change(function(){
		$(".w3p1,.w3p2,.w3p3").css("color",$(this).val());
	})
	//公司名称文字颜色：
	$(".gs3-color").change(function(){
		$(".companyname3").css("color",$(this).val());
	})
	//时间文字颜色：
	$(".sj3-color").change(function(){
		$(".mytime3").css("color",$(this).val());
	})
	
	/*第4块盒子*/
	$(".btn4").click(function(){
		//模板宽度
		$(this).parent().siblings(".template-right").find(".box-back").css("width",$(this).siblings(".set-list").find(".box2w").val());
		//大标题内容：
		$(this).parent().siblings(".template-right").find(".content-title").html($(this).siblings(".set-list").find(".dbt").val());
		//大标题字体大小：
		$(this).parent().siblings(".template-right").find(".content-title").css("font-size",$(this).siblings(".set-list").find(".dbt-size").val()+"px");
		//图片
		$(".img4").attr("src","img/"+$(".tp4").val());
		//图片边框粗细：
		$(".img4").css("border-width",$(".tp4-w").val());
		//名称：
		$(".myname4").html($(".mc4").val());
		//名称字体大小：
		$(".myname4").css("font-size",$(".mc4-size").val()+"px");
		//职务：
		$(".duty").html($(".zw4").val());
		//职务：字体大小：
		$(".duty").css("font-size",$(".zw4-size").val()+"px");
		//横线粗细：
		$(".myline4").css("border-width",$(".hx4").val());
		//段落：
		$(".intro").html($(".dl4").val());
		//段落字体大小：
		$(".intro").css("font-size",$(".dl4-size").val()+"px");
		
	})
	//图片边框颜色：
	$(".tp4-color").change(function(){
		$(".img4").css("border-color",$(this).val());
	})
	//名称颜色：
	$(".mc4-color").change(function(){
		$(".myname4").css("color",$(this).val());
	});
	//职务颜色：
	$(".zw4-color").change(function(){
		$(".duty").css("color",$(this).val());
	})
	//横线颜色：
	$(".hx4-color").change(function(){
		$(".myline4").css("border-color",$(this).val());
	})
	//段落文字颜色：
	$(".dl4-color").change(function(){
		$(".intro").css("color",$(this).val());
	});
	
	/*第5块盒子*/
	$(".btn5").click(function(){
		//模板宽度
		$(this).parent().siblings(".template-right").find(".box-back").css("width",$(this).siblings(".set-list").find(".box2w").val());
		//大标题内容：
		$(this).parent().siblings(".template-right").find(".content-title").html($(this).siblings(".set-list").find(".dbt").val());
		//大标题字体大小：
		$(this).parent().siblings(".template-right").find(".content-title").css("font-size",$(this).siblings(".set-list").find(".dbt-size").val()+"px");
		//图片
		$(".img5").attr("src","img/"+$(".tp5").val());
		//图片边框粗细：
		$(".img5").css("border-width",$(".tp5-size").val());
		//名称：
		$(".myname5").html($(".mc5").val());
		//名称字体大小：
		$(".myname5").css("font-size",$(".mc5-size").val()+"px");
		//职务：
		$(".myduty5").html($(".zw5").val());
		//职务：字体大小：
		$(".myduty5").css("font-size",$(".zw5-size").val()+"px");
		//段落：
		$(".intro5").html($(".dl5").val());
		//段落字体大小：
		$(".intro5").css("font-size",$(".dl5-size").val()+"px");
	})
	//图片边框颜色：
	$(".tp5-color").change(function(){
		$(".img5").css("border-color",$(this).val());
	})
	//名称颜色：
	$(".mc5-color").change(function(){
		$(".myname5").css("color",$(this).val());
	});
	//职务颜色：
	$(".zw5-color").change(function(){
		$(".myduty5").css("color",$(this).val());
	})
	//段落文字颜色：
	$(".dl5-color").change(function(){
		$(".intro5").css("color",$(this).val());
	});
	
	
	/*第6块盒子*/
	$(".btn6").click(function(){
		//模板宽度
		$(this).parent().siblings(".template-right").find(".box-back").css("width",$(this).siblings(".set-list").find(".box2w").val());
		//大标题内容：
		$(this).parent().siblings(".template-right").find(".content-title").html($(this).siblings(".set-list").find(".dbt").val());
		//大标题字体大小：
		$(this).parent().siblings(".template-right").find(".content-title").css("font-size",$(this).siblings(".set-list").find(".dbt-size").val()+"px");
		//图片1
		$(".img6-1").attr("src","img/"+$(".tp6-1").val());
		//图片2
		$(".img6-2").attr("src","img/"+$(".tp6-2").val());
		//图片边框粗细：
		$(".img6").css("border-width",$(".tp6-size").val());
		//名称1：
		$(".myname6-1").html($(".mc6-1").val());
		//名称2：
		$(".myname6-2").html($(".mc6-2").val());
		//名称字体大小：
		$(".myname6").css("font-size",$(".mc6-size").val()+"px");
		//段落1：
		$(".intro6-1").html($(".dl6-1").val());
		//段落2：
		$(".intro6-2").html($(".dl6-2").val());
		//段落字体大小：
		$(".intro6").css("font-size",$(".dl6-size").val()+"px");
		//横线粗细：
		$(".myline6").css("border-width",$(".hx6").val());
	})
	//图片边框颜色：
	$(".tp6-color").change(function(){
		$(".img6").css("border-color",$(this).val());
	})
	//名称颜色：
	$(".mc6-color").change(function(){
		$(".myname6").css("color",$(this).val());
	});
	//段落文字颜色：
	$(".dl6-color").change(function(){
		$(".intro6").css("color",$(this).val());
	});
	//横线颜色：
	$(".hx6-color").change(function(){
		$(".myline6").css("border-color",$(this).val());
	})
	
	/*第7块盒子*/
	$(".btn7").click(function(){
		//模板宽度
		$(this).parent().siblings(".template-right").find(".box-back").css("width",$(this).siblings(".set-list").find(".box2w").val());
		//大标题内容：
		$(this).parent().siblings(".template-right").find(".content-title").html($(this).siblings(".set-list").find(".dbt").val());
		//大标题字体大小：
		$(this).parent().siblings(".template-right").find(".content-title").css("font-size",$(this).siblings(".set-list").find(".dbt-size").val()+"px");
		//图片1
		$(".img7-1").attr("src","img/"+$(".tp7-1").val());
		//图片2
		$(".img7-2").attr("src","img/"+$(".tp7-2").val());
		//图片边框粗细：
		$(".img7").css("border-width",$(".tp7-size").val());
		//名称1：
		$(".myname7-1").html($(".mc7-1").val());
		//名称2：
		$(".myname7-2").html($(".mc7-2").val());
		//名称字体大小：
		$(".myname7").css("font-size",$(".mc7-size").val()+"px");
		//段落1：
		$(".intro7-1").html($(".dl7-1").val());
		//段落2：
		$(".intro7-2").html($(".dl7-2").val());
		//段落字体大小：
		$(".intro7").css("font-size",$(".dl7-size").val()+"px");
		//横线粗细：
		$(".myline7").css("border-width",$(".hx7").val());
	})
	//图片边框颜色：
	$(".tp7-color").change(function(){
		$(".img7").css("border-color",$(this).val());
	})
	//名称颜色：
	$(".mc7-color").change(function(){
		$(".myname7").css("color",$(this).val());
	});
	//段落文字颜色：
	$(".dl7-color").change(function(){
		$(".intro7").css("color",$(this).val());
	});
	//横线颜色：
	$(".hx7-color").change(function(){
		$(".myline7").css("border-color",$(this).val());
	})
	
	
	/*第8块盒子*/
	$(".btn8").click(function(){
		//模板宽度
		$(this).parent().siblings(".template-right").find(".box-back").css("width",$(this).siblings(".set-list").find(".box2w").val());
		//大标题内容：
		$(this).parent().siblings(".template-right").find(".content-title").html($(this).siblings(".set-list").find(".dbt").val());
		//大标题字体大小：
		$(this).parent().siblings(".template-right").find(".content-title").css("font-size",$(this).siblings(".set-list").find(".dbt-size").val()+"px");
		//图片
		$(".img8").attr("src","img/"+$(".tp8").val());
		//图片边框粗细：
		$(".img8").css("border-width",$(".tp8-size").val());
		//段落：
		$(".intro8").html($(".dl8").val());
		//段落字体大小：
		$(".intro8").css("font-size",$(".dl8-size").val()+"px");
		//横线粗细：
		$(".myline8").css("border-width",$(".hx8").val());
	})
	//图片边框颜色：
	$(".tp8-color").change(function(){
		$(".img8").css("border-color",$(this).val());
	})
	//段落文字颜色：
	$(".dl8-color").change(function(){
		$(".intro8").css("color",$(this).val());
	});
	//横线颜色：
	$(".hx8-color").change(function(){
		$(".myline8").css("border-color",$(this).val());
	})
	
	/*第9块盒子*/
	$(".btn9").click(function(){
		//模板宽度
		$(this).parent().siblings(".template-right").find(".box-back").css("width",$(this).siblings(".set-list").find(".box2w").val());
		//大标题内容：
		$(this).parent().siblings(".template-right").find(".content-title").html($(this).siblings(".set-list").find(".dbt").val());
		//大标题字体大小：
		$(this).parent().siblings(".template-right").find(".content-title").css("font-size",$(this).siblings(".set-list").find(".dbt-size").val()+"px");
		//图片
		$(".img9").attr("src","img/"+$(".tp9").val());
		//图片边框粗细：
		$(".img9").css("border-width",$(".tp9-size").val());
		//段落：
		$(".intro9").html($(".dl9").val());
		//段落字体大小：
		$(".intro9").css("font-size",$(".dl9-size").val()+"px");
	})
	//图片边框颜色：
	$(".tp9-color").change(function(){
		$(".img9").css("border-color",$(this).val());
	})
	//段落文字颜色：
	$(".dl9-color").change(function(){
		$(".intro9").css("color",$(this).val());
	});
})
